name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: getrev
        run: |
          echo "revision=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v3
        with:
          push: true
          build-args: |
            REVISION=${{ steps.getrev.outputs.revision }}
          tags: correctiv/faktenforum-frontend

  deploy:
    runs-on: ubuntu-latest
    needs: ["push"]
    steps:
        - uses: luminos-company/portami@v1.1
          with:
            endpoint: 'https://port.hive.beabee.io'
            access_token: ${{ secrets.PORTAINER_ACCESSTOKEN }}
            stack_id: 'faktenforum' # The unique name of the stack like: "cdn_minio"
            prune: true # Prune the stack
            pull: true # Pull the images
